 -module(lab1).
 -export([main/0]).
 main()->io:format(get_solid_of_revolution("ball")),
         io:format(get_solid_of_revolution("Cylinder")),
         io:format(get_solid_of_revolution("Cone")),
         io:format(get_solid_of_revolution("Torus")),
         io:format(get_solid_of_revolution("cube")).

get_solid_of_revolution(Figure) when (Figure == "Ball") or (Figure == "ball") ->
    "Ball:  A ball is the volume space bounded by a sphere; it is also called a solid sphere. It may be a closed ball (including the boundary points that constitute the sphere) or an open ball (excluding them)..\n\n";
get_solid_of_revolution(Figure) when (Figure == "Cylinder") or (Figure == "cylinder") ->
    "Cylinder:  A cylinder has traditionally been a three-dimensional solid, one of the most basic of curvilinear geometric shapes. It is the idealized version of a solid physical tin can having lids on top and bottom.\n\n";
get_solid_of_revolution(Figure) when (Figure == "Cone") or (Figure == "cone") ->
   "Cone:  A cone is a three-dimensional geometric shape that tapers smoothly from a flat base (frequently, though not necessarily, circular) to a point called the apex or vertex.\n\n";
get_solid_of_revolution(Figure) when (Figure == "Torus") or (Figure == "torus") ->
   "Torus:  A torus (plural tori) is a surface of revolution generated by revolving a circle in three-dimensional space about an axis that is coplanar with the circle.\n\n";
get_solid_of_revolution(_) ->
    "Figure is not solid of revolution. Because, a solid of revolution is a solid figure obtained by rotating a plane curve around some straight line (the axis of revolution) that lies on the same plane.\n".
